version: '3'

networks:
    traefik:
        external: true

services:
  cors-anywhere:
    build: .
    container_name: docker-cors-anywhere
    restart: always
    ports:
      - "$CORS_EXTERNAL_PORT:4000"
    volumes:
      - .:/var/www/docker-cors-anywhere
      - /var/www/docker-cors-anywhere/node_modules
    networks:
      - traefik
    labels:
      - traefik.http.routers.docker-cors-anywhere.rule=Host(`cors-anywhere.com.br`)
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cors-anywhere.com.br"
  
  